### ISSUE TITLE
LeaderF fails with "SyntaxWarning: invalid escape sequence '\z'"

### ISSUE THREAD

**Issue by MTRNord** [jdhao/nvim-config#263]
- `nvim --version`: v0.9.5
- terminal emulator and version: Kitty 0.26.5
- Operating system/version: Fedora 39
- Have you read and followed all steps in the [doc](https://github.com/jdhao/nvim-config/tree/master/docs): yes the manual ones plus the things missing in there but present in the bash script
- Output of command `set runtimepath`: 

```
  runtimepath=~/.config/nvim,~/.local/share/nvim/lazy/lazy.nvim,~/.local/share/nvim/lazy/LeaderF,~/.local/share/nvim/lazy/vim-swap,~/.local/share/nvim/lazy/nvim-notify,~/.local/share/nvim/lazy/cmp-nvim-ultisnips,~
/.local/share/nvim/lazy/cmp-emoji,~/.local/share/nvim/lazy/cmp-omni,~/.local/share/nvim/lazy/cmp-buffer,~/.local/share/nvim/lazy/cmp-path,~/.local/share/nvim/lazy/lspkind-nvim,~/.local/share/nvim/lazy/cmp-nvim-lsp
,~/.local/share/nvim/lazy/nvim-cmp,~/.local/share/nvim/lazy/nvim-web-devicons,~/.local/share/nvim/lazy/unicode.vim,~/.local/share/nvim/lazy/targets.vim,~/.local/share/nvim/lazy/vim-highlighturl,~/.local/share/nvim
/lazy/whitespace.nvim,~/.local/share/nvim/lazy/indent-blankline.nvim,~/.local/share/nvim/lazy/which-key.nvim,~/.local/share/nvim/lazy/vim-repeat,~/.local/share/nvim/lazy/vim-indent-object,~/.local/share/nvim/lazy/
hop.nvim,~/.local/share/nvim/lazy/vim-commentary,~/.local/share/nvim/lazy/fidget.nvim,~/.local/share/nvim/lazy/vim-sandwich,~/.local/share/nvim/lazy/lualine.nvim,~/.local/share/nvim/lazy/vim-fugitive,~/.local/shar
e/nvim/lazy/gitlinker.nvim,~/.local/share/nvim/lazy/bufferline.nvim,~/.local/share/nvim/lazy/nord.nvim,~/.local/share/nvim/lazy/plenary.nvim,~/.local/share/nvim/lazy/wilder.nvim,~/.local/share/nvim/lazy/diffview.n
vim,~/.local/share/nvim/lazy/dressing.nvim,~/.local/share/nvim/lazy/dashboard-nvim,~/.local/share/nvim/lazy/gitsigns.nvim,/usr/share/nvim/runtime,~/.local/share/nvim/lazy/cmp-nvim-ultisnips/after,~/.local/share/nv
im/lazy/cmp-emoji/after,~/.local/share/nvim/lazy/cmp-omni/after,~/.local/share/nvim/lazy/cmp-buffer/after,~/.local/share/nvim/lazy/cmp-path/after,~/.local/share/nvim/lazy/cmp-nvim-lsp/after,~/.local/share/nvim/laz
y/indent-blankline.nvim/after,~/.local/share/nvim/lazy/vim-sandwich/after,~/.config/nvim/after,~/.local/state/nvim/lazy/readme
```

**Describe the bug**

The LeaderF steps seem to all fail.

Steps to reproduce the issue:

1. Open nvim
2. Press <leader> f r
3. Boom :bomb: 

**Expected behavior**

It should show me my recently opened files

**Log**

```
Error executing Lua callback: .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#Call, line 18: Vim(return):Error invoking 'python_exec
ute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/home/marcel/.local/share/nvim/lazy/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 821, in start
    the_args.start(arguments, *args, **kwargs)
  File "/var/home/marcel/.local/share/nvim/lazy/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 753, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/var/home/marcel/.local/share/nvim/lazy/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2650, in startExplorer
    self._cleanup()
  File "/var/home/marcel/.local/share/nvim/lazy/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2223, in _cleanup
    self._cli.clear()
  File "/var/home/marcel/.local/share/nvim/lazy/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 174, in clear
    lfCmd("silent! syn clear Lf_hl_match")
  File "/home/marcel/.local/lib/python3.12/site-packages/pynvim/api/nvim.py", line 311, in command
    return self.request('nvim_command', string, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.local/lib/python3.12/site-packages/pynvim/api/nvim.py", line 199, in request
    res = self._session.request(name, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.local/lib/python3.12/site-packages/pynvim/msgpack_rpc/session.py", line 139, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim:/var/home/marcel/.local/share/nvim/lazy/LeaderF/autoload/leaderf/python/leaderf/mruExpl.py:326: SyntaxWarning: invalid escape sequence '\z'
stack traceback:
        [C]: in function 'cmd'
        .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: in function <.../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:16>
```

**Comment by MTRNord** [comment]
Seems to have been a bug only at startup for the first time. Cant reproduce it anymore :thinking:
